### ISSUE TITLE
EGTEA Gaze+ Optical Flow dataset

### ISSUE THREAD

**Issue by faderani** [MichiganCOG/Gaze-Attention#2]
Hello,
I'm just wondering if you have the optical flow of this dataset somewhere uploaded so I don't calculate them again?

**Comment by faderani** [comment]
closing this issue as I have it now. If anyone needs it, please reopen.

**Comment by WPKENAN** [comment]
@faderani where can  i get the dataset

**Comment by WPKENAN** [comment]
> closing this issue as I have it now. If anyone needs it, please reopen.

where can i get the dataset

**Comment by faderani** [comment]
@WPKENAN I calculated flows myself using denseflow: https://github.com/open-mmlab/denseflow

**Comment by kylemin** [comment]
@faderani Thank you for the contribution. @WPKENAN I used [this version](https://github.com/yjxiong/dense_flow) for the optical flow in my experiments. Let me upload my data by next week.

**Comment by kylemin** [comment]
@WPKENAN I've uploaded the flow data: [link](https://drive.google.com/file/d/1SZIfpK59AwSRiliQe1ZGQxLrmwN3tql7/view?usp=sharing). Note that we modified the range of each timestamp to be larger than 24. You can refer to this file: [modify_splits.py](https://drive.google.com/file/d/1CkGJxzukVJPQl6JLawFiWfW6A35uabXe/view?usp=sharing)

**Comment by sandipan211** [comment]
@kylemin the link you uploaded for flow data is not working anymore. Can you please post it again? Thanks.
