### ISSUE TITLE
Gaze data preparation

### ISSUE THREAD

**Issue by faderani** [MichiganCOG/Gaze-Attention#3]
In the dataloader, I noticed gaze data is read from npy files. There should be an intermediate step where you preprocessed gaze data from the text file in the original labels. Is there any instructions on how to do that? I read in the paper you're using one hot encoded approach where value "1" is stored on the x-y grid where gaze is pointing at. I just need a clarification that if my understanding is true.

**Comment by kylemin** [comment]
Hi,
Thank you for your interest.
I have uploaded a python script for generating the pmaps (.npy files): [link](https://drive.google.com/file/d/1IuYXNezX8mJmdRWq0CS4cSaOWFidVurw/view?usp=sharing).
I hope it helps.

**Comment by faderani** [comment]
Thank you so much. Very helpful!
