### ISSUE TITLE
Whats pmap?

### ISSUE THREAD

**Issue by ppriyank** [MichiganCOG/Gaze-Attention#5]
From where do we obtain the pmaps (as used in training)?

**Comment by kylemin** [comment]
Please refer to the previous issue: [link](https://github.com/MichiganCOG/Gaze-Attention/issues/3)

**Comment by ppriyank** [comment]
Thank you, I should have searched better.

**Comment by sandipan211** [comment]
Hi @ppriyank @kylemin 

> Please refer to the previous issue: [link](https://github.com/MichiganCOG/Gaze-Attention/issues/3)



> Thank you, I should have searched better.

The link you provided is expired. Can you kindly reupload the file again where you preprocessed and got the .npy files? Thanks!
