### ISSUE TITLE
EGTEA preparation

### ISSUE THREAD

**Issue by FedericoCaspani** [MichiganCOG/Gaze-Attention#8]
Hi, I have a problem with the dataset preparation. In particular your code takes as input single rgb images but the Egetea dataset provides only videos (which they call cropped clips)as you can see in the readme of the EGTEA Gaze + dataset:
![EGTEA](https://github.com/MichiganCOG/Gaze-Attention/assets/79706352/271eef28-d119-4cfa-89f8-ed53facd3d1b)
Can you explain how you obtained such images? Or can you provide a link to that images?
Thanks

**Comment by kylemin** [comment]
Hi,

They provide links to raw videos (~28GB): [link](https://www.dropbox.com/s/uwwj6wb1j4rsm02/video_links.txt?dl=0). After downloading all the videos, you can extract the frames (clips) following the annotations.
For example, for the video named [P21-R04-ContinentalBreakfast.mp4](https://www.dropbox.com/s/qyk99gucy73k4uh/P21-R04-ContinentalBreakfast.mp4?dl=0), you can extract a training clip ([line](https://github.com/MichiganCOG/Gaze-Attention/blob/main/dataset/EGTEA/train_split1.txt#L4)) that spans from frame:17468 to frame:17667.

Thank you,
Kyle

**Comment by FedericoCaspani** [comment]
Ok, let me reformulate my question to be more precise.
In the dataset.py file at line 62: `rimg = cv2.imread(os.path.join(self.datapath, 'images_rgb', cn, '%04d.jpg' % (start_idx+i)), -1)`
The function imread reads a single image in format jpg, not a mp4 file.
The train_split1.txt file refers to a list of clips which are small videos that can be downloaded from the dataset page [https://cbs.ic.gatech.edu/fpv/](url) and are called trimmed action clips.
I still don't understand what are these jpg files. Are these jpg files the single frames that compose the trimmed action clips?

Thank you for your help,
Federico

**Comment by kylemin** [comment]
Hi Federico,

Our code reads a sequence of images for each clip. Please extract the frames using ffmpeg or cv2.

If you are not familiar with video processing, please refer to [this link](https://github.com/facebookresearch/SlowFast/blob/main/slowfast/datasets/DATASET.md#ava) or [this](https://github.com/facebookresearch/TimeSformer/blob/main/timesformer/datasets/DATASET.md#something-something-v2) and see how they extract the frames for the video datasets.

Thank you,
Kyle

**Comment by FedericoCaspani** [comment]
Thank you that was very helpfull.
Federico
